[package]
name = "wasm-custom-sections"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.26"
wasm-bindgen = "0.2.49"
